### ISSUE TITLE
D&D: Droping a Part in a Package not doing what is expected

### ISSUE THREAD

**Issue by stephanelacrampe** [eclipse-syson/syson#227] opened 2024-04-23 22:29 UTC
When Drag & Dropping a Part in a Package on from the general view diagram, it works well, the part is moved under the package including in the explorer view.
But when Drag & Dropping a Part from the explorer view to a Package on the diagram view, visually it looks like it is working, but the Part is actually not moved under the package in the explorer view.

**Comment by AxelRICHARD** [comment] 2024-04-24 07:18
Duplicate of #223

**Closed by AxelRICHARD** 2024-04-24 07:18 UTC

**Comment by stephanelacrampe** [comment] 2024-04-24 21:51
I understand how this may be a duplicate of #223 . Nevertheless, I am wondering the following: Let's say you create an empty General View. Now let's say you drag & drop a part in this empty diagram, but this part is under a package (or a package hierarchy). Should the tool prevent you from drag and dropping the part in the empty diagram? That would be a strange behavior. If this part is under a hierarchy of 10 packages, then it cannot be dropped on the diagram until all the hierarchy of package has been manually dropped, one by one, on the diagram?

**Comment by AxelRICHARD** [comment] 2024-04-25 07:06
> I understand how this may be a duplicate of #223 . Nevertheless, I am wondering the following: Let's say you create an empty General View. Now let's say you drag & drop a part in this empty diagram, but this part is under a package (or a package hierarchy). Should the tool prevent you from drag and dropping the part in the empty diagram? That would be a strange behavior. If this part is under a hierarchy of 10 packages, then it cannot be dropped on the diagram until all the hierarchy of package has been manually dropped, one by one, on the diagram?

No, you will still be able to d&d into the diagram background.

**Comment by stephanelacrampe** [comment] 2024-04-25 17:50
Let me continue this conversation on #223 then as I don't agree with one of the statements that is made on #223
